 [project]
name = "hagent"
version = "0.1.2"
description = ""
authors = [
    {name = "Farzaneh Rabiei", email = "frabieik@ucsc.edu"},
    {name = "Jose Renau", email = "renau@ucsc.edu"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "pyyaml>=6.0.2",
    "litellm>=1.59.10",
    "diskcache>=5.6.3",
    "legacy-cgi>=2.6.2", # needed for litlellm with python 3.13 (soon to be fixed, I hope)
    "pyslang>=8.0.0",
    "speechrecognition>=3.14.1",
    "sounddevice>=0.5.1",
    "numpy>=2.2.2",
    "rapidfuzz>=3.12.1",
    "ruamel-yaml>=0.18.10",
    "fusepy>=3.0.1",
    "networkx>=3.5",
    "chromadb>=1.0.12",
    "docker>=7.1.0",
    "transformers>=4.30.0",
    "torch>=2.7.1",
    "sentence-transformers>=4.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-cov>=6.0.0",
    "ruff>=0.12.0",
    "pydoc-markdown>=4.8.2",
]

[tool.ruff]
line-length = 130

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest-testmon>=2.1.3",
]

[tool.pytest.ini_options]
testpaths = ["hagent"]
filterwarnings = [
    "ignore::DeprecationWarning",
   "ignore::UserWarning"
]

[tool.coverage.run]
omit = [
    "hagent/core/tests/*",
    "hagent/step/**/tests/*",
    "hagent/tool/**/tests/*",
]
